name: hardware_report
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.8.14
  - pip:
    - matplotlib==3.6.2
    - pandas==1.5.1
    - psutil==5.9.4
    - reportlab==3.6.12
    - requests==2.28.1
    - seaborn==0.12.2