name: charity
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.8.14
  - pip:
    - IPython==8.8.0
    - watchdog==2.2.1
    - matplotlib==3.6.2
    - nltk==3.7
    - pandas==1.5.1
    - pre-commit==2.21.0
    - scikit-learn==1.1.0
    - streamlit==1.16.0
